module.exports = {
  surahs: [
      { name: "Al-Fātihah", pageGreen: 1 },
      { name: "Al-Baqarah", pageGreen: 2 },
      { name: "Āl-ʿImrān", pageGreen: 50 },
      { name: "An-Nisāʾ", pageGreen: 77 },
      { name: "Al-Māʾidah", pageGreen: 106 },
      { name: "Al-Anʿām", pageGreen: 128 },
      { name: "Al-Aʿrāf", pageGreen: 151 },
      { name: "Al-Anfāl", pageGreen: 177 },
      { name: "At-Tawbah", pageGreen: 187 },
      { name: "Yūnus", pageGreen: 208 },
      { name: "Hūd", pageGreen: 221 },
      { name: "Yūsuf", pageGreen: 235 },
      { name: "Ar-Raʿd", pageGreen: 249 },
      { name: "Ibrāhīm", pageGreen: 255 },
      { name: "Al-Ḥijr", pageGreen: 262 },
      { name: "An-Naḥl", pageGreen: 267 },
      { name: "Al-Isrāʾ", pageGreen: 282 },
      { name: "Al-Kahf", pageGreen: 293 },
      { name: "Maryam", pageGreen: 305 },
      { name: "Ṭā-Hā", pageGreen: 312 },
      { name: "Al-Anbiyāʾ", pageGreen: 322 },
      { name: "Al-Ḥajj", pageGreen: 332 },
      { name: "Al-Muʾminūn", pageGreen: 342 },
      { name: "An-Nūr", pageGreen: 350 },
      { name: "Al-Furqān", pageGreen: 359 },
      { name: "Ash-Shuʿarā", pageGreen: 367 },
      { name: "An-Naml", pageGreen: 377 },
      { name: "Al-Qaṣaṣ", pageGreen: 385 },
      { name: "Al-ʿAnkabūt", pageGreen: 396 },
      { name: "Ar-Rūm", pageGreen: 404 },
      { name: "Luqmān", pageGreen: 411 },
      { name: "As-Sajdah", pageGreen: 415 },
      { name: "Al-Aḥzāb", pageGreen: 418 },
      { name: "Sabaʾ", pageGreen: 428 },
      { name: "Fāṭir", pageGreen: 434 },
      { name: "Yā-Sīn", pageGreen: 440 },
      { name: "As-Ṣāffāt", pageGreen: 446 },
      { name: "Sād", pageGreen: 453 },
      { name: "Az-Zumar", pageGreen: 458 },
      { name: "Ghāfir", pageGreen: 467 },
      { name: "Fuṣṣilat", pageGreen: 477 },
      { name: "Ash-Shūrā", pageGreen: 483 },
      { name: "Az-Zukhruf", pageGreen: 489 },
      { name: "Ad-Dukhān", pageGreen: 496 },
      { name: "Al-Jāthiyah", pageGreen: 499 },
      { name: "Al-Aḥqāf", pageGreen: 502 },
      { name: "Muḥammad", pageGreen: 507 },
      { name: "Al-Fatḥ", pageGreen: 511 },
      { name: "Al-Ḥujurāt", pageGreen: 515 },
      { name: "Qāf", pageGreen: 518 },
      { name: "Adh-Dhāriyāt", pageGreen: 520 },
      { name: "At-Ṭūr", pageGreen: 523 },
      { name: "An-Najm", pageGreen: 526 },
      { name: "Al-Qamar", pageGreen: 528 },
      { name: "Ar-Raḥmān", pageGreen: 531 },
      { name: "Al-Wāqiʿah", pageGreen: 534 },
      { name: "Al-Ḥadīd", pageGreen: 537 },
      { name: "Al-Mujādilah", pageGreen: 542 },
      { name: "Al-Ḥashr", pageGreen: 545 },
      { name: "Al-Mumtaḥanah", pageGreen: 549 },
      { name: "As-Ṣaff", pageGreen: 551 },
      { name: "Al-Jumuʿah", pageGreen: 553 },
      { name: "Al-Munāfiqūn", pageGreen: 554 },
      { name: "At-Taghābun", pageGreen: 556 },
      { name: "At-Ṭalāq", pageGreen: 558 },
      { name: "At-Taḥrīm", pageGreen: 560 },
      { name: "Al-Mulk", pageGreen: 562 },
      { name: "Al-Qalam", pageGreen: 564 },
      { name: "Al-Ḥāqqah", pageGreen: 566 },
      { name: "Al-Maʿārij", pageGreen: 568 },
      { name: "Nūḥ", pageGreen: 570 },
      { name: "Al-Jinn", pageGreen: 572 },
      { name: "Al-Muzzammil", pageGreen: 574 },
      { name: "Al-Muddaththir", pageGreen: 575 },
      { name: "Al-Qiyāmah", pageGreen: 577 },
      { name: "Al-Insān", pageGreen: 578 },
      { name: "Al-Mursalāt", pageGreen: 580 },
      { name: "An-Nabaʾ", pageGreen: 582 },
      { name: "An-Nāziʿāt", pageGreen: 583 },
      { name: "ʿAbasa", pageGreen: 585 },
      { name: "At-Takwīr", pageGreen: 586 },
      { name: "Al-Infiṭār", pageGreen: 587 },
      { name: "Al-Muṭaffifīn", pageGreen: 587 },
      { name: "Al-Inshiqāq", pageGreen: 589 },
      { name: "Al-Burūj", pageGreen: 590 },
      { name: "At-Ṭāriq", pageGreen: 591 },
      { name: "Al-Aʿlā", pageGreen: 591 },
      { name: "Al-Ghāshiyah", pageGreen: 592 },
      { name: "Al-Fajr", pageGreen: 593 },
      { name: "Al-Balad", pageGreen: 594 },
      { name: "Ash-Shams", pageGreen: 595 },
      { name: "Al-Layl", pageGreen: 595 },
      { name: "Ad-Ḍuḥā", pageGreen: 596 },
      { name: "Ash-Sharḥ", pageGreen: 596 },
      { name: "At-Tīn", pageGreen: 597 },
      { name: "Al-ʿAlaq", pageGreen: 597 },
      { name: "Al-Qadr", pageGreen: 598 },
      { name: "Al-Bayyinah", pageGreen: 598 },
      { name: "Az-Zalzalah", pageGreen: 599 },
      { name: "Al-ʿĀdiyāt", pageGreen: 599 },
      { name: "Al-Qāriʿah", pageGreen: 600 },
      { name: "At-Takāthur", pageGreen: 600 },
      { name: "Al-ʿAsr", pageGreen: 601 },
      { name: "Al-Humazah", pageGreen: 601 },
      { name: "Al-Fīl", pageGreen: 601 },
      { name: "Quraysh", pageGreen: 602 },
      { name: "Al-Māʿūn", pageGreen: 602 },
      { name: "Al-Kawthar", pageGreen: 602 },
      { name: "Al-Kāfirūn", pageGreen: 603 },
      { name: "An-Naṣr", pageGreen: 603 },
      { name: "Al-Masad", pageGreen: 603 },
      { name: "Al-Ikhlāṣ", pageGreen: 604 },
      { name: "Al-Falaq", pageGreen: 604 },
      { name: "An-Nās", pageGreen: 604 },
  ],
  reciters: [
      { name: "Muhammad Al-Luhaidan" },
      { name: "Yasser Al-Dossary" },
      { name: "Maher Al Muaiqly" },
      { name: "Saad Alghamdi" },
      { name: "Saud Al Shuraim" },
      { name: "Abdulrahman Al-Sudais" },
      { name: "Abu Baker Shatri" },
      { name: "Ahmed Al Ajami" },
      { name: "Salah Bukatir" },
      { name: "Abdel Aziz Al Ahmed" },
      { name: "Mohammad Jibreel" },
      { name: "Mohammad Ayyub" },
      { name: "Abdur Rashid Sufi" },
      { name: "Adel Al Kalbani" },
      { name: "Salah Albudair" },
    ]
}